[package]
name = "xmltui"
version = "0.0.1"
edition = "2024"
license = "MIT"
description = "xmltui is a framework for building Terminal User Interfaces (TUIs) using a web-like approach."
readme = "README.md"
repository = "https://github.com/afuentesan/xmltui/tree/main/xmltui"
documentation = "https://github.com/afuentesan/xmltui/tree/main/xmltui"
keywords = ["tui", "terminal", "framework"]
categories = ["command-line-interface"]
authors = ["Ángel Fuente <awpakj@gmail.com>"]

[dependencies]
xmltui-lib = { path = "../xmltui-lib" }
clap = { version = "4.6.1", features = [ "derive" ] }
anyhow = "1.0.104"
